# this file uses prebuilt image in dockerhub
name: al-folio
services:
  jekyll:
    image: amirpourmand/al-folio:slim
    #build: .
    ports:
      - 8080:8080
      - 35729:35729
    command: /srv/jekyll/bin/entry_point.sh
    volumes:
      - .:/srv/jekyll
      - bundle-cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  bundle-cache:
